# Generated by Django 3.2.16 on 2022-11-16 14:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0012_auto_20200505_2029'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='face_128d_features',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='captchamodel',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lived_dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lived_users', to='dormitories.dormitory', verbose_name='居住宿舍'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='users/face_photo/', verbose_name='人脸照片')),
                ('features', models.TextField(null=True, verbose_name='特征数据')),
                ('features_mask', models.TextField(null=True, verbose_name='特征数据(口罩)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户详情信息',
                'verbose_name_plural': '用户详情信息',
            },
        ),
        migrations.CreateModel(
            name='QQLoginTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=32, verbose_name='授权令牌')),
                ('expires_in', models.IntegerField(verbose_name='授权令牌的有效期，单位为秒')),
                ('refresh_token', models.CharField(max_length=32, verbose_name='授权续期需要提供的参数')),
                ('openid', models.CharField(max_length=32, verbose_name='用户OpenID')),
                ('update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_login', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'QQ登陆TOKEN',
                'verbose_name_plural': 'QQ登陆TOKEN',
            },
        ),
    ]
