# Generated by Django 3.0.1 on 2022-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0014_auto_20221012_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='标题'),
        ),
    ]
